config/routes.rb
Bookmark::Application.routes.draw do
  resources :categories

  get "profile/index"
  get "profile/new"
  get "profile/logout"
  post "profile/signup"
  post "profile/sign"
  get "profile/sign"
  
  match 'sites/cat/:id' => 'sites#cat'

  resources :sites
  match 'profile/cat/:id' => 'profile#cat'

  root :to => 'profile#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
    belongs_to :profile
    has_many :sites
end

app/models/profile.rb
class Profile < ActiveRecord::Base
    has_many :sites
    has_many :categories

    def self.mysite(id)
       Site.where(:profile_id=>id)
    end
end

app/models/site.rb
class Site < ActiveRecord::Base
    belongs_to :profile
    belongs_to :category

    def category_name
        if Category.exists?(self.category_id)
            model = Category.find(self.category_id)
            model.title
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout "category"
  # GET /categories
  # GET /categories.json
  def index
    p = Profile.where(:username=>session[:username]).first
    @categories = p.categories.all 
    if(!p.nil?)
        @sites = p.sites.all
        if(p.id==1)
            @categories = Category.all
        end
    else
        redirect_to '/' and return
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = Category.new
    @profile_id = Profile.where(:username=>session[:username]).first.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @profile_id = Profile.where(:username=>session[:username]).first.id
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        redirect_to "/categories" and return
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        redirect_to "/categories" and return
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

#
  def new
  end

  def signup
        @p = Profile.new(:username => params[:username])
        @p.password = params[:password]
        @p.save
        redirect_to "/"
  end

  def index
        if(!session[:username].nil?)
            redirect_to "/sites" and return
        end
  end

  def sign
    @p = Profile.where(:username => params[:username], :password => params[:password]).first
    if(!@p.nil?)
        session[:username] = params[:username]
        redirect_to "/sites"
    else
        redirect_to "/"
    end
  end

  def logout
        session[:username]= nil
        redirect_to "/"
  end

  def cat
        @category = Category.find(params[:id]).title
        render :layout => 'nothing' and return
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  layout "site"

  # GET /sites
  # GET /sites.json
  def index
    p = Profile.where(:username=>session[:username]).first
    if(!p.nil?)
        @sites = Profile.mysite(p.id)
        if(p.id==1)
            @sites = Site.find(:all, :order => "created_at DESC")
        end
    else
        redirect_to '/' and return
    end
    @site = Site.new
    @profile_id = Profile.where(:username=>session[:username]).first.id
    @categories = p.categories.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = Site.new
    @profile_id = Profile.where(:username=>session[:username]).first.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @profile_id = Profile.where(:username=>session[:username]).first.id
    @site = Site.find(params[:id])
    @desc = Site.find(params[:id]).desc
    p = Profile.where(:username=>session[:username]).first
    @categories = p.categories.all
    render :layout => 'category'
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
        if Category.exists?(:title => params[:category_id])
            c = Category.where(:title => params[:category_id]).first    
        else
            c = Category.new(:title => params[:category_id]) 
        end
        p = Profile.where(:username => session[:username]).first
        c.profile_id = p.id
        c.save
        @site.category_id = c.id
        @site.save
        redirect_to "/sites" and return
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end


  # PUT /sites/1
  # PUT /sites/1.json
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
        redirect_to "/sites" and return
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end


  def cat
    p = Profile.where(:username=>session[:username]).first
    if(!p.nil?)
        @sites = p.sites.where(:category_id => params[:id])
    else
        redirect_to '/' and return
    end
    @site = Site.new
    @profile_id = Profile.where(:username=>session[:username]).first.id
    @categories = p.categories.all

    render "index"

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, :placeholder=>'category' %>
  </div>
  <div class="field">
    <textarea name="category[desc]" placeholder="description" ><%= @category.desc %></textarea>
  </div>
  <!--
  <div class="field">
    <%= f.label :profile_id %><br />
    <%= f.number_field :profile_id %>
  </div>
  -->
  <input type="hidden" name="category[profile_id]" value="<%=@profile_id%>">
  <div class="actions">
    <input type="submit" name="submit" value="Submit" class="btn-large btn-primary">
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<table>
  <tr>
    <th width="10%">Category</th>
    <th width="40%">Description</th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><font color="red"><%= category.title %><font></td>
    <td style="text-align:center;"><i><%= category.desc %><i></td>
    <td><button><%= link_to 'Edit', edit_category_path(category) %></button></td>
    <td><button><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></button></td>
  </tr>
<% end %>
</table>

<br />
<a href="/categories/new"><button class="btn-primary btn">New Category</button></a>

app/views/categories/new.html.erb
<%= render 'form' %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @category.title %>
</p>

<p>
  <b>Desc:</b>
  <%= @category.desc %>
</p>

<p>
  <b>Profile:</b>
  <%= @category.profile_id %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bookmarking Sites!</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Onlinekarta is a free service that lets you save, categorize, and manage your links/urls anywhere and share them easily. Never depend on your browser or laptop again!">
    <link rel="image_src" href="/assets/onlinekarta.png" />
    <meta name="author" content="">

    <!-- Le styles -->
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "bootstrap" %>
<!--  <%= javascript_include_tag :defaults %> -->
  <%= csrf_meta_tags %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>
    
    <!--
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div
    -->

    <div class="container">

    <%= yield :header %>

        <%= yield %>



    <div id="name" class="name" style="height:140px;">
    </div>
    <hr>
       <footer>
           <span> written in Ruby on Rails, hosted on Heroku, here the <a href="https://github.com/evnpr/bookmark">Source Code</a></span>
       </footer>


    </div> <!-- /container -->



    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster 
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>
    -->

  </body>
</html>

app/views/layouts/category.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bookmark</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Onlinekarta is a free service that lets you save, categorize, and manage your links/urls anywhere and share them easily. Never depend on your browser or laptop again!">
    <link rel="image_src" href="/assets/onlinekarta.png" />
    <meta name="author" content="">

    <!-- Le styles -->
  <%= stylesheet_link_tag    "bootstrap", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "bootstrap" %>
<!--  <%= javascript_include_tag :defaults %> -->
  <%= csrf_meta_tags %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>
    
    <!--
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div
    -->

    <div class="container">

    <div id="name" class="row">
    <i class="icon-search"></i>
    <a href="/" class="span1 btn"  id="btn_add_site"><span>Home</span></a>
    <a href="/sites" class="span2 btn"  id="btn_add_site"><span>View MySites</span></a>
    <a href="/profile/logout" class="span2 btn" style="float:right"><span>Log Out</span></a>
    <span style="float:right">hi, <b><%= session[:username] %></b>!</span>
    </div>
    <hr>
        
        <%= yield %>


    <div id="name" class="name" style="height:140px;">
    </div>
    <hr>
       <footer>
           <span> written in Ruby on Rails, hosted on Heroku, here the <a href="https://github.com/evnpr/bookmark">Source Code</a></span>
       </footer>

    </div> <!-- /container -->


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster 
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>
    -->
    <script type="text/javascript" charset="utf-8">
            function add_site(){
                $("#index_site").toggle("fast");
                $("#new_site").toggle("hide");
                $("#btn_add_site").toggle();
                $("#btn_view_mysites").toggle();
            }
                
            function submit_new_site(){
                site_link = document.getElementById('site_link').value ;
                site_desc = document.getElementById('site_desc').value ;
                site_profile_id = document.getElementById('site_profile_id').value ;
                $.post("/sites/create",{sitelink:'site_link', sitedesc:'site_desc', siteprofileid:'site_profile_id'},function(result){
                    $("#content").html(result);
                });
            }
    </script>
  </body>
</html>

app/views/layouts/nothing.html.erb
<%= yield %>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Bookmarking Sites</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Onlinekarta is a free service that lets you save, categorize, and manage your links/urls anywhere and share them easily. Never depend on your browser or laptop again!">
    <link rel="image_src" href="/assets/onlinekarta.png" />
    <meta name="author" content="">
 <link href="/assets/bootstrap.css?body=1" media="all" rel="stylesheet" type="text/css" /> 
    <!-- Le styles -->
  <%= stylesheet_link_tag    "bootstrap", "style", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "bootstrap" %>
  <%= javascript_include_tag "jquery.masonry.min" %>
<!--  <%= javascript_include_tag :defaults %> -->
  <%= csrf_meta_tags %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="../assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>
    
    <!--
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div
    -->

    <div class="container">

    <div id="name" class="row">
    <i class="icon-search"></i>
    <a href="/" class="span1 btn"  id="btn_add_site"><span>Home</span></a>
    <a class="span1 btn" onclick="add_site()" id="btn_add_site"><span>Add Site</span></a>
    <a class="span2 btn" onclick="add_site()" id="btn_view_mysites" style="display:none"><span>View MySites</span></a>
    <a href="/categories" class="span2 btn"><span>Manage Categories</span></a>
    <a href="/profile/logout" class="span2 btn" style="float:right"><span>Log Out</span></a>
    <span style="float:right">hi, <b><%= session[:username] %></b>!</span>
    </div>
    <hr>
        
        <%= yield %>


    <div id="name" class="name" style="height:140px;">
    </div>
    <hr>
       <footer>
           <span> written in Ruby on Rails, hosted on Heroku, here the <a href="https://github.com/evnpr/bookmark">Source Code</a></span>
       </footer>

    </div> <!-- /container -->


    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster 
    <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script>
    -->
    <script type="text/javascript" charset="utf-8">
            function add_site(){
                $("#index_site").toggle("fast");
                $("#new_site").toggle("hide");
                $("#btn_add_site").toggle();
                $("#btn_view_mysites").toggle();
            }
                
            function submit_new_site(){
                site_link = document.getElementById('site_link').value ;
                site_desc = document.getElementById('site_desc').value ;
                site_profile_id = document.getElementById('site_profile_id').value ;
                $.post("/sites/create",{sitelink:'site_link', sitedesc:'site_desc', siteprofileid:'site_profile_id'},function(result){
                    $("#content").html(result);
                });
            }
    </script>
  </body>
</html>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, :placeholder=>'Title' %>
  </div>
  <div class="field">
    <%= f.text_field :link, :placeholder=>'url' %>
  </div>
  <div class="field">
    <textarea name="site[desc]" placeholder="description"><%= @desc %></textarea>
  </div>
  <div id="name" class="field">
      <input type="hidden" name="site[category_id]"/>
      <input type="text" name="category_id" placeholder="category" id="category" />
      <br><br>
      <br><br>
            <% for category in @categories %>
              <code style="cursor:pointer; margin-right: 20px;" onClick="inputCat('<%= category.title %>')"><%= category.title %> </code>
            <% end %>
      <br><br>
      <br><br>
  </div>
  <!--
  <div class="field">
    <%= f.label :profile_id %><br />
    <%= f.number_field :profile_id %>
  </div>
  -->
  <input type="hidden" name="site[profile_id]" value="<%=@profile_id%>">
  <div class="actions">
    <input type="submit" name="submit" value="Submit" class="btn-large btn-primary">
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
    function inputCat(category){
        document.getElementById('category').value = category;
    }
</script>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<div id="index_site" class="row" style="padding-left:20px">
<% @categories.each do |cat| %>
<a href="/sites/cat/<%= cat.id %>"><code><%= cat.title %></code></a>
<% end %>

<br><br>
<div id="container" class="clearfix">

   
<% @sites.each do |site| %>

  <div class="box col1 well">

		      <b><a href="
		     
		<% sitelink = site.link %>
		<% s = sitelink.to_s() %>
		<% if(s.include?("http://")) %>
		     <%= s %>
		<% else %>
		     http://<%= s %>
		<% end %>      

		      "><%= site.title %></a></b>
      <p><i> <%= site.desc %></i></p>
<!--        <button class="btn"> <%= link_to 'Show', site %> </button> -->
        <button onclick='window.location.replace("/sites/<%=site.id%>/edit")' class="btn"> <%= link_to 'Edit', edit_site_path(site) %> </button>
        <button class="btn"> <%= link_to 'Destroy', site, confirm: 'Are you sure?', method: :delete %> </button>
        <br>
        <br>
      category : <a href="/sites/cat/<%=site.category_id%>" style="color: red">

      <% if(!site.category_id.nil?) %> 
      
      <%= site.category_name %>

      <% end %>


      </a>
      <br>
      <font size="1" color="grey"><%= site.created_at %></font>
      <br>
      <br>
<!--
      <div id="name" class="name" style="float:right">
      <script>var fbShare = {
      url: '<%= site.link %>',
      size: 'small',
      badge_text: 'C0C0C0',
      badge_color: 'bebebe',
      google_analytics: 'true'
      }</script>
      <script src="http://widgets.fbshare.me/files/fbshare.js"></script>
      </div>
      <div id="name" class="name">
         <a href="https://twitter.com/share" class="twitter-share-button" data-url="<%= site.link %>" data-text="<%= site.desc %>">Tweet</a>
         <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      </div>
-->
  </div>




<% end %>

</div>



</div> <!-- #container -->


<script>
  $(function(){
    
    $('#container').masonry({
      itemSelector: '.box'
    });

  });
</script>

    



<div id="new_site" style="display:none">
<%= render 'form' %>
</div>

    

app/views/sites/new.html.erb
<%= render 'form' %>

<a onclick="history.back()"><span class="btn">Back</span></a>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Link:</b>
  <%= @site.link %>
</p>

<p>
  <b>Desc:</b>
  <%= @site.desc %>
</p>

<p>
  <b>Profile:</b>
  <%= @site.profile_id %>
</p>


<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>